let license; 
let badge; 

function generateMarkdown(data) {

  if (data.license == 'MIT'){
    license = `
    MIT License 
    
    Copyright (c) ${data.person}
    
    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:
    
    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.
    
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
    
    You can find more information on this license here "https://choosealicense.com/licenses/mit/"`; 

  badge = 'https://img.shields.io/badge/License-MIT-blue'

  }else if (data.license == 'Apache-License-2.0') {
    license =  `Copyright ${data.person}

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at
  
        http://www.apache.org/licenses/LICENSE-2.0
  
      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.`

    badge = "https://img.shields.io/badge/License-Apache--License--2.0-blue"

  }else if (data.license == 'Mozilla Public License 2.0'){
    license = 
      `Licensed under the Mozilla Public License 2.0
      More Information can be found on "https://choosealicense.com/licenses/mpl-2.0/" ` 

    let badge = "https://img.shields.io/badge/License-Mozilla%20Public%20License%202.0-blue"

  }else if (data.license == 'Boost Software License 1.0'){
    license =  
      `
      Boost Software License - Version 1.0 - August 17th, 2003 

      Permission is hereby granted, free of charge, to any person or organization
      obtaining a copy of the software and accompanying documentation covered by
      this license (the "Software") to use, reproduce, display, distribute,
      execute, and transmit the Software, and to prepare derivative works of the
      Software, and to permit third-parties to whom the Software is furnished to
      do so, all subject to the following:
    
      The copyright notices in the Software and this entire statement, including
      the above license grant, this restriction and the following disclaimer,
      must be included in all copies of the Software, in whole or in part, and
      all derivative works of the Software, unless such copies or derivative
      works are solely in the form of machine-executable object code generated by
      a source language processor.
    
      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
      FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
      SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
      FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
      ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
      DEALINGS IN THE SOFTWARE.`

    badge = "https://img.shields.io/badge/License-Boost%20Software%20License%201.0-blue"
  }else 
    license = 'none'; 
  
  
  return `
  ![badge](${badge}) 
  
  # ${data.project}
  
  ## Description
  ${data.description}

  ## Table of Contents 
  - [Installation](#installation)
  - [Usage](#usage)
  - [License](#license)
  - [Contribute](#contribute)
  - [Tests](#tests)
  - [Questions](#questions)



  ## Installation
  > ${data.dependencies}
  

  ## Usage
  ${data.usage}
 

  ## License
  ${license}
  

  ## Contribute
  ${data.contribution}


  ## Tests
  ${data.test}


  ## Questions
  If you have any questions please feel free to reach out to ${data.person} directly via email at ${data.email} or on Github at https://github.com/${data.name}. 
  

`; 
 
}



module.exports = generateMarkdown;



